environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run coverage
  - npm run codecov
build: off